### ISSUE TITLE
Extension thinks that .lua files are directories

### ISSUE THREAD

**Issue by lavender-sys** [Sleitnick/AeroGameFramework-VSCE#2]
I recently installed AeroGameFramework in VS Code and I got this error when using the tree explorer. 

`ENOTDIR: not a directory, stat '/Users/coleshoemaker/Library/CloudStorage/iCloud Drive/Documents/Project SIlver/Home/src/Client/Modules/PID.lua/init.lua'`

It seems like it thinks a .lua file is a directory?

**Comment by Sleitnick** [comment]
@Dog2puppy <strike>are you on Mac?</strike> You are obviously on mac from the path shown haha. Thanks for the report. I had another Mac user report the same issue. Looking into it now.

**Comment by lavender-sys** [comment]
For some reason my email reply didn’t make a comment, but yes, I am on MacOS. MacOS Catalina to be specific.

**Comment by lavender-sys** [comment]
@Sleitnick Did you find the root cause of this? Just looking through your code (that I have no idea what it does, lol) it looks like this might be the issue? https://github.com/Sleitnick/AeroGameFramework-VSCE/blob/6dbaa84969daaf305f29d513da211c86cb1a47ae/src/agfExplorer.ts#L83

**Comment by Sleitnick** [comment]
I don't necessarily think it's that for sure. The good news is that I have a MacBook Pro & was able to reproduce the issue on my end. I'll look into fixing this later this evening.

My running theory from glancing at the code is line 79, right above what you posted. It might be trying to scan through every file, which just returns nothing on Windows but errors on Mac. But I need to test that later.

**Comment by Sleitnick** [comment]
This has been fixed.

The issue was that it was trying to check for an "init" file within every _file_, not just directories. On Windows, this is fine, but it throws an error on Mac. The code has been changed to explicitly verify that it's scanning on a directory and not a file.

Verify you have version 0.0.14 for the proper fix.
